### ISSUE TITLE
Cannot compile scanner on Mac OS X 10.6.4

### ISSUE THREAD

**Issue by spitfire** [RJ/playdar-core#31]
I cannot build neither prefpane nor core (with scanner), I have taglib and taglib-extras installed from macports (in /opt/local prefix) (taglib @1.6.3  taglib-extras @1.0.1)
Scanner from playdar-core complains about "libtag.a", which doesn't exist on my system.
this is the log for playdar-core module, log for playdar.prefpane follows:

$ make scanner
g++ `taglib-config --cflags` `taglib-config --libs` -o playdar_modules/library/priv/taglib_driver/taglib_json_reader playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:9:28: error: taglib/fileref.h: No such file or directory
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:10:24: error: taglib/tag.h: No such file or directory
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp: In function ‘std::string ext2mime(const std::string&)’:
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:65: error: ‘cerr’ was not declared in this scope
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp: In function ‘std::string scan_file(const char_)’:
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:114: error: ‘TagLib’ has not been declared
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:114: error: expected `;' before ‘f’
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:115: error: ‘f’ was not declared in this scope
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:116: error: ‘TagLib’ has not been declared
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:116: error: ‘tag’ was not declared in this scope
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:120: error: ‘TagLib’ has not been declared
playdar_modules/library/priv/taglib_driver/taglib_json_reader.cpp:120: error: ‘properties’ was not declared in this scope
make: *_\* [playdar_modules/library/priv/taglib_driver/taglib_json_reader] Error 1
###### ##LOG FOR PREFPANE

$ xcodebuild 
=== BUILD NATIVE TARGET Playdar.prefPane OF PROJECT Playdar.prefPane WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies

Ld build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/x86_64/Playdar normal x86_64
    cd /Volumes/Dokumenty/mieszko/playdar.prefpane
    setenv MACOSX_DEPLOYMENT_TARGET 10.5
    /Xcode4/usr/bin/clang -arch x86_64 -bundle -isysroot /Xcode4/SDKs/MacOSX10.5.sdk -L/Volumes/Dokumenty/mieszko/playdar.prefpane/build -L/Volumes/Dokumenty/mieszko/playdar.prefpane/build/Cellar/taglib -F/Volumes/Dokumenty/mieszko/playdar.prefpane/build -F/Volumes/Dokumenty/mieszko/playdar.prefpane -filelist /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/x86_64/Playdar.LinkFileList -mmacosx-version-min=10.5 -framework Cocoa -framework PreferencePanes -framework Sparkle -o /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/x86_64/Playdar
ld: warning: directory not found for option '-L/Volumes/Dokumenty/mieszko/playdar.prefpane/build/Cellar/taglib'
Alloca array size must be i32
  %seed = alloca i32, %struct.NSConstantString\* @_unnamed_cfstring_, align 2097152 ; <i32*> [#uses=1]
Alloca array size must be i32
  %1 = alloca %struct.__objcFastEnumerationState, %struct.NSConstantString\* @_unnamed_cfstring_, align 2097152 ; <%struct.__objcFastEnumerationState_> [#uses=5]
Alloca array size must be i32
  %2 = alloca [16 x i8_], %struct.NSConstantString\* @_unnamed_cfstring_, align 2097152 ; <[16 x i8_]_> [#uses=2]
Alloca array size must be i32
  %url = alloca %struct.__CFURL_, %struct.NSConstantString_ @_unnamed_cfstring_, align 2097152 ; <%struct.__CFURL*_> [#uses=3]
Intrinsic prototype has incorrect number of arguments!
void (i8_, i8, i64, i32, i1)\* @llvm.memset.p0i8.i64
Broken module found, compilation aborted!
Stack dump:
0.      Running pass 'Function Pass Manager' on module 'ld-temp.o'.
1.      Running pass 'Module Verifier' on function '@"\01-[OrgPlaydarPreferencePane startAtLogin:]"'
clang: error: linker command failed due to signal 6 (use -v to see invocation)
Command /Xcode4/usr/bin/clang failed with exit code 250

Ld build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/Playdar normal i386
    cd /Volumes/Dokumenty/mieszko/playdar.prefpane
    setenv MACOSX_DEPLOYMENT_TARGET 10.5
    /Xcode4/usr/bin/clang -arch i386 -bundle -isysroot /Xcode4/SDKs/MacOSX10.5.sdk -L/Volumes/Dokumenty/mieszko/playdar.prefpane/build -L/Volumes/Dokumenty/mieszko/playdar.prefpane/build/Cellar/taglib -F/Volumes/Dokumenty/mieszko/playdar.prefpane/build -F/Volumes/Dokumenty/mieszko/playdar.prefpane -filelist /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/Playdar.LinkFileList -mmacosx-version-min=10.5 -framework Cocoa -framework PreferencePanes -framework Sparkle -o /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/Playdar
ld: warning: directory not found for option '-L/Volumes/Dokumenty/mieszko/playdar.prefpane/build/Cellar/taglib'
ld: duplicate symbol .objc_class_name_OrgPlaydarPreferencePane in /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/main.o and /Volumes/Dokumenty/mieszko/playdar.prefpane/build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/main.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Command /Xcode4/usr/bin/clang failed with exit code 1

*\* BUILD FAILED **

The following build commands failed:
        Ld build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/x86_64/Playdar normal x86_64
        Ld build/Playdar.prefPane.build/Release/Playdar.prefPane.build/Objects-normal/i386/Playdar normal i386

**Comment by spitfire** [comment]
BTW. I also tried to build with xcode 3.2.x of course.
I have erlang installed via macports (erlang @R14A)
